-- Attendance sessions: one immutable attendance window per guild and local date.
-- UTC timestamps are stored as ISO 8601 strings generated by the application.
-- Because all absolute times use the same timezone-aware UTC format, lexical
-- ordering safely enforces start_at < late_at < close_at here.
CREATE TABLE attendance_sessions (
    id INTEGER PRIMARY KEY AUTOINCREMENT,

    guild_id TEXT NOT NULL,

    attendance_date TEXT NOT NULL,

    start_at TEXT NOT NULL,

    late_at TEXT NOT NULL,

    close_at TEXT NOT NULL,

    status TEXT NOT NULL
        CHECK (
            status IN (
                'SCHEDULED',
                'OPEN',
                'CLOSED',
                'CANCELLED'
            )
        ),

    opened_at TEXT,

    closed_at TEXT,

    cancelled_at TEXT,

    cancel_reason TEXT,

    start_announced_at TEXT,

    close_announced_at TEXT,

    created_at TEXT NOT NULL,

    updated_at TEXT NOT NULL,

    FOREIGN KEY (guild_id)
        REFERENCES guild_settings(guild_id)
        ON DELETE RESTRICT,

    -- Prevent duplicate sessions for the same guild-local attendance date.
    UNIQUE (guild_id, attendance_date),

    CHECK (
        start_at < late_at
        AND late_at < close_at
    )
);


-- Supports finding sessions that still need status or close-time processing.
CREATE INDEX idx_attendance_sessions_guild_status_close
ON attendance_sessions (
    guild_id,
    status,
    close_at
);


-- Attendance session members: a snapshot of the eligible members at session
-- creation time so later member registration or deactivation does not rewrite
-- the historical target set.
CREATE TABLE attendance_session_members (
    id INTEGER PRIMARY KEY AUTOINCREMENT,

    session_id INTEGER NOT NULL,

    member_id INTEGER NOT NULL,

    included_at TEXT NOT NULL,

    FOREIGN KEY (session_id)
        REFERENCES attendance_sessions(id)
        ON DELETE RESTRICT,

    FOREIGN KEY (member_id)
        REFERENCES members(id)
        ON DELETE RESTRICT,

    -- A member can be included only once in a session snapshot.
    UNIQUE (session_id, member_id)
);


-- Attendance records: the final per-member outcome for a session.
-- excuse_request_id is intentionally nullable without a foreign key until the
-- future excuse_requests table is introduced by its own migration.
CREATE TABLE attendance_records (
    id INTEGER PRIMARY KEY AUTOINCREMENT,

    session_id INTEGER NOT NULL,

    member_id INTEGER NOT NULL,

    status TEXT NOT NULL
        CHECK (
            status IN (
                'PRESENT',
                'LATE',
                'ABSENT',
                'EXCUSED_LATE',
                'EXCUSED_ABSENT'
            )
        ),

    checked_at TEXT,

    source TEXT NOT NULL
        CHECK (
            source IN (
                'USER',
                'AUTO',
                'ADMIN'
            )
        ),

    excuse_request_id INTEGER,

    note TEXT,

    created_at TEXT NOT NULL,

    updated_at TEXT NOT NULL,

    FOREIGN KEY (session_id)
        REFERENCES attendance_sessions(id)
        ON DELETE RESTRICT,

    FOREIGN KEY (member_id)
        REFERENCES members(id)
        ON DELETE RESTRICT,

    -- A member has one attendance outcome per session.
    UNIQUE (session_id, member_id)
);


CREATE INDEX idx_attendance_records_session_status
ON attendance_records (
    session_id,
    status
);


CREATE INDEX idx_attendance_records_member_session
ON attendance_records (
    member_id,
    session_id
);


-- Score events: append-only ledger for all point changes.
-- Total score is derived from SUM(delta), keeping members free of cached score
-- state and making reversals/audits explicit.
CREATE TABLE score_events (
    id INTEGER PRIMARY KEY AUTOINCREMENT,

    guild_id TEXT NOT NULL,

    member_id INTEGER NOT NULL,

    event_type TEXT NOT NULL,

    delta INTEGER NOT NULL,

    reference_type TEXT,

    reference_id INTEGER,

    dedup_key TEXT NOT NULL,

    description TEXT NOT NULL,

    created_by_discord_id TEXT,

    created_at TEXT NOT NULL,

    reversed_event_id INTEGER,

    FOREIGN KEY (guild_id)
        REFERENCES guild_settings(guild_id)
        ON DELETE RESTRICT,

    FOREIGN KEY (member_id)
        REFERENCES members(id)
        ON DELETE RESTRICT,

    FOREIGN KEY (reversed_event_id)
        REFERENCES score_events(id)
        ON DELETE RESTRICT,

    -- Deduplication keys prevent awarding the same point event twice.
    UNIQUE (dedup_key)
);


CREATE INDEX idx_score_events_member_created
ON score_events (
    member_id,
    created_at
);


CREATE INDEX idx_score_events_guild_member
ON score_events (
    guild_id,
    member_id
);


CREATE INDEX idx_score_events_reference
ON score_events (
    reference_type,
    reference_id
);


-- Audit logs: administrator actions and manual data corrections.
-- JSON snapshots remain TEXT so SQLite does not require JSON extensions.
CREATE TABLE audit_logs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,

    guild_id TEXT NOT NULL,

    actor_discord_id TEXT NOT NULL,

    action_type TEXT NOT NULL,

    target_type TEXT NOT NULL,

    target_id TEXT NOT NULL,

    before_json TEXT,

    after_json TEXT,

    reason TEXT NOT NULL,

    created_at TEXT NOT NULL,

    FOREIGN KEY (guild_id)
        REFERENCES guild_settings(guild_id)
        ON DELETE RESTRICT
);


CREATE INDEX idx_audit_logs_guild_created
ON audit_logs (
    guild_id,
    created_at
);


CREATE INDEX idx_audit_logs_target
ON audit_logs (
    target_type,
    target_id
);
